export const CHANGE_CONNECTION_STATUS = 'common/CHANGE_CONNECTION_STATUS';
export type CHANGE_CONNECTION_STATUS = typeof CHANGE_CONNECTION_STATUS;

export const INCREMENT_NETWORK_CALLS = 'common/INCREMENT_NETWORK_CALLS';
export type INCREMENT_NETWORK_CALLS = typeof INCREMENT_NETWORK_CALLS;
